
Name            = 'FsToml.CompilerService'
OutputType      = 'Library'
FrameworkVersion = '4.6.1'


Files = [
    { None = "paket.references" },
    { Compile = "Transform.fs" },
    { Compile = "AssemblyInfo.fs"}
]

Dependencies = [
    { Reference = "System" },
    { Reference = "System.Core" },
    { Reference = "System.Numerics" },
    { Reference = "System.Xml" },
    { Reference = "System.Xml.Linq" },
    { Package = "FSharp.Compiler.Service" },
    { Package = "FSharp.Compiler.Service.ProjectCracker" },
    { Package = "Paket.Core" }
]

# configurations
[ Debug ]
    DebugSymbols = true
    DebugType = 'full'
    Optimize = false
    Tailcalls = false
    OutputPath = 'bin\Debug'
    Constants = [ 'DEBUG', 'TRACE' ]
    WarningLevel = 3

[ Release ]
    DebugType = 'pdbonly'
    Optimize = true
    Tailcalls = true
    OutputPath = 'bin\Release'
    Constants = [ 'TRACE' ]
    WarningLevel = 3






