
FsTomlVersion   = '0.0.1'
Name            = 'FsToml.CompilerService'
AssemblyName    = 'FsToml.CompilerService'
RootNamespace   = 'FsToml.CompilerService'
Guid            = 'cb1359ac-44ed-46ec-8eee-7ac0f73c79f2'
OutputType      = 'Library'
FSharpCore      = '4.4.0.0'


Files = [
    { None = "paket.references" },
    { Compile = "Transform.fs" },
    { Compile = "AssemblyInfo.fs"}
]

References = [
    { Framework = "System" },
    { Framework = "System.Core" },
    { Framework = "System.Numerics" },
    { Framework = "System.Xml" },
    { Framework = "System.Xml.Linq" },
    { Package = "FSharp.Compiler.Service" },
    { Package = "FSharp.Compiler.Service.ProjectCracker" },
    { Package = "Paket.Core" },
    { Project = "..\\src\\FsToml\\FsToml.fsproj" }
]

# configurations
[ Debug ]
    DebugSymbols = true
    DebugType = 'full'
    Optimize = false
    Tailcalls = false
    OutputPath = 'bin\Debug'
    Constants = [ 'DEBUG', 'TRACE' ]
    WarningLevel = 3

[ Release ]
    DebugType = 'pdbonly'
    Optimize = true
    Tailcalls = true
    OutputPath = 'bin\Release'
    Constants = [ 'TRACE' ]
    WarningLevel = 3






